export const statusChart = [
    {
        id: '4',
        status: 'Shipped',
        company: 'Lana Fashions',
        created: '2022-12-03',
        po_sent: '2022-12-03',
        po_accepted: '2022-12-03',
        inv_sent: '2022-12-03',
        inv_paid: '2022-12-04',
        shipped: '2022-12-05',
        completed: false,
        tracking_id: 'F013456',
        shipping_vendor: 'FedEx'
    },
    {
        id: '2',
        status: 'PO Sent',
        company: 'Lana Fashions',
        created: '2022-12-01',
        po_sent: '2022-12-01',
        po_accepted: '',
        inv_sent: '',
        inv_paid: '',
        shipped: '',
        completed: false,
        tracking_id: '',
        shipping_vendor: 'FedEx'
    },
    {
        id: '5',
        status: 'Invoice Sent',
        company: 'Lana Fashions',
        created: '2022-12-05',
        po_sent: '2022-12-06',
        po_accepted: '2022-12-07',
        inv_sent: '2022-12-08',
        inv_paid: '',
        shipped: '',
        completed: false,
        tracking_id: '',
        shipping_vendor: 'FedEx'
    },

    {
        id: '1',
        status: 'Created',
        company: 'Schmo Resale',
        created: '2022-12-01',
        po_sent: '',
        po_accepted: '',
        inv_sent: '',
        inv_paid: '',
        shipped: '',
        completed: false,
        tracking_id: '',
        shipping_vendor: 'UPS'
    },
    {
        id: '3',
        status: 'Invoice Paid',
        company: 'Schmo Resale',
        created: '2022-11-20',
        po_sent: '2022-11-20',
        po_accepted: '2022-11-21',
        inv_sent: '2022-11-21',
        inv_paid: '2022-11-23',
        shipped: '',
        completed: false,
        tracking_id: '',
        shipping_vendor: 'USPS'
    },
]

export const clients = [
    {
        name: 'Joe Schmo',
        company: 'Schmo Resale',
        address: '202 Corporate Park',
        city: 'Schenectady',
        state: 'NY',
        zip: '12301',
        email : 'joe.schmo@schmoeresale.com',
        phone: '555-555-5555',
        addresses : [
            {
                name: 'Mary Schmo',
                company: '',
                address: '100 Home Address',
                city: 'Schenectady',
                state: 'NY',
                zip: '12301',
                phone: '555-555-5555',
            }
        ]
    },
    {
        name: 'Lana Lang',
        company: 'Lana Fashions',
        address: '10-101 Main Street',
        city: 'Los Angeles',
        state: 'CA',
        zip: '90001',
        email : 'lana.lang@lanafashions.com',
        phone: '212-777-7777',
        addresses : [
            {
                name: 'Joe Lang',
                company: '',
                address: '100 Home Address',
                city: 'Los Angeles',
                state: 'CA',
                zip: '90022',
                phone: '212-777-7777',
            }
        ]
    },
]

export const idata = [
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type : 'Sandals',
            style : 'Green',
            count : 3,
            retail : 170,
            wholesale : 59,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type :	'Sandals',
            style : 'Light Green',
            count : 3,
            retail : 170,
            wholesale : 59,
            purchase: 10,
			 
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Sandals',
            style : 'Red',
            count : 5,
            retail : 375,
            wholesale : 150,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Sandals',
            style : 'Blue',
            count : 2,
            retail : 350,
            wholesale : 122,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Alexander McQueen',
            type : 'Sandals',
            style : 'Green',
            count : 4,
            retail : 290,
            wholesale : 101,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Alexander McQueen',
            type : 'Sandals',
            style : 'Black',
            count : 2,
            retail : 350,
            wholesale : 105,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Alexander McQueen',
            type : 'Sandals',
            style : 'White',
            count : 4,
            retail : 350,
            wholesale : 105,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Alexander McQueen',
            type : 'Sneakers',
            style : 'Black/White',
            count : 6,
            retail : 720,
            wholesale : 216,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Alexander McQueen',
            type : 'Low-top sneakers',
            style : 'White',
            count : 8,
            retail : 540,
            wholesale : 135,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Baseball Cap',
            style : 'Neon Green',
            count : 4,
            retail : 480,
            wholesale : 168,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Moncler',
            type : 'Baseball Cap',
            style : 'Black',
            count : 10,
            retail : 390,
            wholesale : 117,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Shorts',
            style : 'Neon Green',
            count : 3,
            retail : 890,
            wholesale : 356,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Sweat Shirt',
            style : 'Black',
            count : 2,
            retail : 1320,
            wholesale : 396,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Tee Shirt',
            style : 'Black',
            count : 2,
            retail : 920,
            wholesale : 276,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type : 'Sweatpants',
            style : 'Light Yellow',
            count : 2,
            retail : 850,
            wholesale : 255,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type : 'Sneakers',
            style : 'White/Black',
            count : 3,
            retail : 510,
            wholesale : 102,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type : 'Sneakers',
            style : 'Red/White',
            count : 3,
            retail : 510,
            wholesale : 102,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Saint Laurent',
            type : 'Sneakers',
            style : 'White/Canvas',
            count : 2,
            retail : 575,
            wholesale : 173,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Saint Laurent',
            type : 'Sneakers',
            style : 'White/LTHR',
            count : 1,
            retail : 745,
            wholesale : 223,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Versace',
            type : 'Sandals',
            style : 'Green',
            count : 3,
            retail : 325,
            wholesale : 98,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Sandals',
            style : 'Red',
            count : 1,
            retail : 375,
            wholesale : 113,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Fendi',
            type : 'Sandals',
            style : 'Red',
            count : 2,
            retail : 430,
            wholesale : 129,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Burberry Jacket',
            type : 'Mens jacket',
            style : 'Black/Blue',
            count : 1,
            retail : 1960,
            wholesale : 580,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Givenchy',
            type : 'Baseball cap',
            style : 'Neon Green',
            count : 3,
            retail : 480,
            wholesale : 143,
            purchase: 10,
    },
    { 		description: '',
			images: '',
			size: 'L',
			sku: '123-456',
			vendor : 'Palm Angels',
            type : 'Sweatpants',
            style : 'Blue',
            count : 1,
            retail : 560,
            wholesale : 168,
            purchase: 10,
    }
]